package:
    name: eman2
    #version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
    version: 3.0

source:
    git_url: git@github.com:cryoem/eman2.git 
    git_branch: conda

build:
    number: 13

requirements:
    build:
        - zlib
        - cmake
        - pyopengl <3.1.1
        - numpy
        - ftgl
        - freetype >2.5
        - gsl
        - boost
        - fftw
        - hdf5
        - libtiff >4
        - jpeg >8
        - libpng
        - python <3
    run:
        - mpi4py
        - python <3
        - numpy
        - freetype >2.5
        - matplotlib
        - gsl
        - boost
        - fftw
        - hdf5
        - ipython
        - pyqt >4.10
        - qt <5
        - pyopengl <3.1.1
        - ftgl
        - bsddb
        - readline
        - libtiff >4
        - jpeg >8
        - libpng

about:
  home: http://blake.bcm.edu/emanwiki
  license: GPL2
  license_file: LICENSE.txt
  summary: A scientific image processing software suite with a focus on CryoEM and CryoET.

extra:
  maintainers:
    - Steve Ludtke
    - James Michael Bell
    - Vernon Williams
    - Tunay Durmaz
