package:
    name: eman2
    version: 3.0.0

source:
    git_url: git@github.com:cryoem/eman2.git 
    git_branch: conda-wip

build:
    number: 0
    rpaths:
        - lib/python2.7/site-packages/EMAN2
        - lib/python2.7/site-packages/sparx
        - lib/

requirements:
    build:
        - zlib
        - cmake
        - pyopengl
        - numpy
        - ftgl 2.1.3
        - freetype
        - gsl 2.1
        - boost
        - fftw 3.3.4
        - hdf5
        - libtiff
        - jpeg
        - libpng
        - python <3
    run:
        - python <3
        - numpy
        - freetype
        - matplotlib
        - boost
        - fftw 3.3.4
        - ipython
        - pyqt
        - pyopengl
        - ftgl 2.1.3
        - bsddb
        - readline
        - libtiff
        - jpeg
        - libpng
        - gsl 2.1
        - hdf5

about:
  home: http://blake.bcm.edu/emanwiki
  license: GPL2
  license_file: LICENSE
  summary: A scientific image processing software suite with a focus on CryoEM and CryoET.

extra:
  maintainers:
    - Steve Ludtke
    - James Michael Bell
    - Vernon Williams
    - Tunay Durmaz
