package:
    name: eman2
    version: 3.0.0

source:
    git_url: git@github.com:cryoem/eman2.git 
    git_branch: conda

build:
    number: 19
    rpaths:
        - lib/python2.7/site-packages/EMAN2/
        - lib/python2.7/site-packages/sparx/
        - lib/

requirements:
    build:
        - zlib
        - cmake
        - pyopengl 3.1.0
        - numpy 1.11
        - ftgl 2.1.3
        - freetype 2.5.2
        - gsl 1.16
        - boost 1.51.0
        - fftw 3.3.4
        - hdf5 1.8.14
        - libtiff >4
        - jpeg >8
        - libpng 1.6.24
        - python <3
    run:
        - mpi4py
        - python <3
        - numpy 1.11
        - freetype 2.5.2
        - matplotlib
        - gsl 1.16
        - boost 1.51.0
        - fftw 3.3.4
        - hdf5 1.8.14
        - ipython
        - pyqt 4.11.4
        - qt <5
        - pyopengl 3.1.0
        - ftgl 2.1.3
        - bsddb
        - readline 6.2.5
        - libtiff >4
        - jpeg >8
        - libpng 1.6.24

about:
  home: http://blake.bcm.edu/emanwiki
  license: GPL2
  license_file: LICENSE
  summary: A scientific image processing software suite with a focus on CryoEM and CryoET.

extra:
  maintainers:
    - Steve Ludtke
    - James Michael Bell
    - Vernon Williams
    - Tunay Durmaz
