package:
  name: jpeg
  version: 9d

source:
  fn: jpegsrc.v8d.tar.gz
  url: http://www.ijg.org/files/jpegsrc.v9b.tar.gz

build:
  number: 2             # [osx]

about:
  home: http://www.ijg.org/
  license: Custom free software license
  summary: read/write jpeg COM, EXIF, IPTC medata
