package:
  name: numpy
  version: 1.11.0

source:
  fn: numpy-1.11.0.tar.gz
  url: https://pypi.python.org/packages/e0/4c/515d7c4ac424ff38cc919f7099bf293dd064ba9a600e1e3835b3edefdb18/numpy-1.11.1.tar.gz
  md5: 2f44a895a8104ffac140c3a70edbd450

requirements:
  build:
    - python
  run:
    - python

about:
  home: http://numpy.scipy.org/
  license: BSD
